#!/usr/bin/env bash
# bootstrap-sample.sh — build a throwaway corpus from examples/sample-corpus so a
# newcomer can get a cited answer in minutes, on synthetic data, before ingesting
# their own. Markdown + pandoc only: no Ollama, no OCR, no API key for the build.
#
#   scripts/bootstrap-sample.sh            # build into examples/.sandbox (git-ignored)
#   LIFE_AGENT_SAMPLE_DIR=/tmp/la scripts/bootstrap-sample.sh   # build elsewhere
#
# Idempotent: pkm's content-addressed cache makes a re-run a no-op.
set -euo pipefail

# Resolve through symlinks so $root is always the repo, however this was invoked.
root="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
sandbox="${LIFE_AGENT_SAMPLE_DIR:-$root/examples/.sandbox}"
corpus="$root/examples/sample-corpus"

export LIFE_AGENT_KB="$sandbox/kb"
export PKM_CONFIG="$sandbox/pkm.yaml"
store="$sandbox/pkm-store"

if ! command -v pandoc >/dev/null 2>&1; then
  echo "error: pandoc is not installed — the sample corpus is extracted with pandoc." >&2
  echo "       install it (e.g. 'sudo pacman -S pandoc' / 'apt install pandoc' /" >&2
  echo "       'brew install pandoc'), then re-run this script." >&2
  exit 1
fi
pandoc_version="$(pandoc --version | head -1 | awk '{print $2}')"

echo "life-agent sample bootstrap"
echo "  repo:    $root"
echo "  sandbox: $sandbox   (git-ignored; delete it to start over)"
echo "  pandoc:  $pandoc_version"
echo

mkdir -p "$sandbox" "$LIFE_AGENT_KB/config" "$store"

# pkm config — pandoc only (the sample is pure markdown), version pinned to the
# installed pandoc so the content-addressed cache key is honest on this machine.
cat > "$PKM_CONFIG" <<EOF
# Generated by scripts/bootstrap-sample.sh for the sample corpus. Throwaway.
root_dir: $store
extractors:
  pandoc:
    version: "$pandoc_version"
    config: {}
EOF

# Data-source registry — one filetree root pointing at the synthetic corpus.
cat > "$LIFE_AGENT_KB/config/data-sources.yaml" <<EOF
# Generated by scripts/bootstrap-sample.sh. Points at the synthetic sample corpus.
version: 1
roots:
  - id: sample
    kind: filetree
    path: $corpus
    include: ["**/*.md"]
    tags: [sample]
    enabled: true
EOF

# Owner profile — who "I"/"my" is. This is what stops the partner's decoy record
# (Charles Babbage, ID 987654321) being reported as the owner's. See examples/README.md.
cat > "$LIFE_AGENT_KB/owner.md" <<'EOF'
# Owner profile (sample)

I am Ada Lovelace. My national identity number is 123456789. My partner is
Charles Babbage; documents about him are not about me.
EOF

# A PII denylist so commits made with this sample KB active aren't blocked by the
# fail-closed guard. (For your real work, copy it into your real $LIFE_AGENT_KB.)
cp -n "$root/config/pii-patterns.txt.example" "$LIFE_AGENT_KB/pii-patterns.txt" 2>/dev/null || true

run() { echo "+ pkm $*"; uv run --project "$root" pkm --config "$PKM_CONFIG" "$@"; }

echo "== building the sample corpus =="
run migrate
echo "+ ingest_sources.py"
uv run --project "$root" python "$root/scripts/ingest_sources.py"
run extract --producer pandoc      # markdown → text; pandoc only, no models
run chunk --backfill               # index any artifact not chunked inline
run rebuild-index                  # make the chunks searchable (FTS)

echo
echo "Done. The sample corpus is built. Ask it something:"
echo
echo "    export LIFE_AGENT_KB=$LIFE_AGENT_KB"
echo "    export PKM_CONFIG=$PKM_CONFIG"
echo "    bin/ask-live \"what is my national ID number?\""
echo
echo "(bin/ask-live needs ANTHROPIC_API_KEY for answer synthesis — see SETUP.md.)"
echo "More questions to try: examples/README.md"
